name: CI/CD
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Execute format
        run: deno fmt --check

      - name: Execute lint
        run: deno lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: deno install && deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'todo-effect'
          entrypoint: 'server.js'
          root: '.'
